__title__ = "smansaancol"
__description__ = "Scraping Web Elearning SMA N 1 Muara Ancalong"
__url__ = "https://github.com/MR-X-junior/smansaancol"
__version__ = "0.0.1"
__author__ = "Rahmat adha"
__author_email__ = "rahmadadha11@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright Rahmat adha"
